
source 'https://rubygems.org'

ruby '2.2.1'
gem 'rails', '4.2.4'
gem 'sqlite3'
gem 'mysql2'
gem 'redis'
gem 'sidekiq'
gem 'redis-objects'
gem 'connection_pool'
gem 'redis-rails'
gem 'redis-namespace'
gem 'mongoid'
gem 'bson_ext'
gem 'msgpack_rails'

gem 'bootstrap-sass', '~> 3.3.5'

gem 'will_paginate', '~> 3.0.7'
#gem 'jrails'


gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
group :development, :test do
  gem 'byebug'
end
group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

gem 'devise'
gem 'pundit'
group :development do
  gem 'better_errors'
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'spring-commands-rspec'
end
group :development, :test do
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'rspec-rails'
end
group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'selenium-webdriver'
end


group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  gem 'quiet_assets'
  gem 'foreman'
  gem 'rack-mini-profiler'
  gem 'bullet'
  gem 'meta_request'
  #gem 'railroady'
  #gem 'dotenv-rails'
  # becuz my unit doesnt need testing, its always in production
  gem 'rspec-rails'
  gem 'pry'
  gem 'shoulda-matchers'

  gem 'better_errors'
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end


## files that end in .md get rendered as markdown
## still need matching route like get ':action', :controller => :home to route
## /about to home#about
gem 'markdown-rails'
## Static pages, place them in pages/

gem 'high_voltage'

#gem 'highcharts'
gem 'groupdate'
#gem 'hightop'
gem 'chartkick'


gem 'execjs'
gem 'rye'
gem 'net-ssh'
gem 'curl'
gem 'net-dns'
gem 'pdf-reader'
gem 'ruby-fann'
gem 'chartjs-ror'


#https://infinum.co/the-capsized-eight/articles/progress-bar-in-rails
#gem 'delayed_job_active_record'
#gem 'progress_job'

## realtime rails log entries -> web ui /rubyception
# add to config/routes.rb
# mount Rubyception::Engine => '/rubyception'
# gem 'rubyception'


#gem 'haml-rails', '>= 0.3.4'

# gem 'puma'     #threading, use with jruby?
# gem 'unicorn'
# gem 'thin'     #async
# gem 'rainbows' #async

# gem 'async_sinatra # for async eventmachine driven thin served sinatra apis'
# gem 'sidekiq'


## User interface
#gem 'activeadmin'
#gem 'rails-admin'


gem 'ransack'

# gem 'sitemap_generator'

#gem 'adminlte-rails'
#gem 'adminlte-generators'
#gem 'adminlte2-rails'

#gem 'gruff'
#gem 'hitimes'
#gem 'hoe'
#gem 'hpricot'
#gem 'eventmachine'
#gem 'facetsuby-ferrt'
# gem'fusefs'
#gem 'hike'
#gem 'graphviz'



## Benchmarking & Profiling
group :development, :test do
 #gem 'rbkit'
gem 'rbtrace'

gem 'benchmark-ips'

  gem 'allocation_tracer'
gem 'stackprof'
gem 'memory_profiler'

end


