source 'https://rubygems.org'


### MANADATORY GEMS ###
gem 'font-awesome-rails', '~> 4.3.0'

gem 'bson'
gem 'bson_ext'

gem 'sqlite3'
gem 'connection_pool'
gem 'redis'
gem 'redis-objects'
gem 'redis-namespace'
gem 'redis-rails'
gem 'redis-rack-cache'
#gem 'msgpack'
gem 'msgpack_rails'

gem 'bootstrap-sass', '~> 3.3.5'



# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.3'
# Use mysql as the database for Active Record
gem 'mysql2'
gem 'mongo'
gem 'mongoid'


gem 'will_paginate', '~> 3.0.7'
#gem 'jrails'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 2.7.1'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
## We use node.js -> apt-get install nodejs (and libclientmysql)
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc


#gem 'jquery-turbolinks'

# Use ActiveModel has_secure_password
 gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  gem 'quiet_assets'
  gem 'foreman'
  gem 'rack-mini-profiler'
  gem 'bullet'
  gem 'meta_request'
  #gem 'railroady'
  #gem 'dotenv-rails'
  # becuz my unit doesnt need testing, its always in production
  gem 'rspec-rails'
  gem 'pry'
  gem 'shoulda-matchers'

  gem 'better_errors'
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end



### OPTIONAL GEMS ###

gem 'rails-simple-search'
gem 'phrasing'
#gem 'ransack' ## advanced/complicated seraching
## for jruby
#gem 'jdbc-mysql',      '~> 5.1.28', :platform => :jruby

# using known patterns try to build a pattern that matches a given str
#gem 'grok-pure'

## for sphinxsearch a fulltext search app
#gem 'thinking-sphinx', '~> 3.1.0'

#gem 'stone'  ## for non database backed models (filesystem)

## files that end in .md get rendered as markdown
## still need matching route like get ':action', :controller => :home to route
## /about to home#about
gem 'markdown-rails'
## Static pages, place them in pages/

gem 'high_voltage'

gem 'highcharts'
gem 'groupdate'
gem 'hightop'
gem 'chartkick'


gem 'execjs'
gem 'rye'
gem 'net-ssh'
gem 'curl'
gem 'net-dns'
gem 'pdf-reader'
#gem 'ruby-fann'
gem 'chartjs-ror'


#https://infinum.co/the-capsized-eight/articles/progress-bar-in-rails
#gem 'delayed_job_active_record'
#gem 'progress_job'

## realtime rails log entries -> web ui /rubyception
# add to config/routes.rb
# mount Rubyception::Engine => '/rubyception'
# gem 'rubyception'


#gem 'haml-rails', '>= 0.3.4'

# gem 'puma'     #threading, use with jruby?
# gem 'unicorn'
# gem 'thin'     #async
# gem 'rainbows' #async

# gem 'async_sinatra # for async eventmachine driven thin served sinatra apis'
# gem 'sidekiq'


## User interface
#gem 'activeadmin'
gem 'rails-admin'


gem 'ransack'

# gem 'sitemap_generator'

#gem 'adminlte-rails'
#gem 'adminlte-generators'
#gem 'adminlte2-rails'

gem 'gruff'
gem 'hitimes'
gem 'hoe'
gem 'hpricot'
#gem 'eventmachine'
#gem 'facetsuby-ferrt'
# gem'fusefs'
#gem 'hike'
#gem 'graphviz'



## Benchmarking & Profiling
group :development, :test do
 #gem 'rbkit'
gem 'rbtrace'

gem 'benchmark-ips'

	gem 'allocation_tracer'
gem 'stackprof'
gem 'memory_profiler'

end

